[package]
name = "scale-value-to-borrowed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scale-value="*"
scale-borrow={path="/home/gilescope/git/scale-borrow", features=[]}

[features]
bitvec = ["scale-borrow/bitvec"]